version: '3.7'
services:
  openssh:
    image: 'openssh-server'
    hostname: 'openssh'
    domainname: 'example.com'
    restart: 'always'
    volumes:
    - 'openssh:/etc/ssh'
    - '${PWD}/openssh-server/openssh-server/sshd_config:/etc/ssh/sshd_config:ro'
    - '${PWD}/openssh-server/openssh-server/ssh_config:/etc/ssh/ssh_config:ro'
    - '${HOME}/.ssh/id_rsa.pub:/home/ubuntu/.ssh/authorized_keys:ro'
    cap_add:
    - 'SYS_CHROOT'
    - 'SETGID'
    - 'SETUID'
    - 'CHOWN'
    expose:
    - '22'
    entrypoint: ['/usr/sbin/sshd']
    command: ['-ddd']
  nginx:
    image: 'nginx:1.17.3'
    restart: 'always'
    ports:
    - '22:22'
    volumes:
    - '${PWD}/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
volumes:
  openssh:
